apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-pod-sheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
      schedulerName: my-scheduler
      nodeSelector:
        scheduler-node: my-scheduler-master-node
